# yaml-language-server: $schema=../plugins/tmux-which-key/config.schema.yaml
command_alias_start_index: 200
keybindings:
  # root_table: C-Space  # conflicts with prefix, leave disabled
  prefix_table: Space
title:
  style: align=centre,bold
  prefix: "tmux"
  prefix_style: "fg=green,align=centre,bold"
position:
  x: R
  y: P
custom_variables: []
macros:
  - name: reload-config
    commands:
      - 'display "Loading config..."'
      - "source-file $HOME/.config/tmux/tmux.conf"
      - 'display "Config reloaded!"'
items:
  - name: Run
    key: space
    command: command-prompt
  - name: Last window
    key: tab
    command: last-window
  - name: Last pane
    key: "`"
    command: last-pane
  - separator: true
  - name: Split down
    key: j
    command: "splitw -v -c #{pane_current_path}"
  - name: Split right
    key: l
    command: "splitw -h -c #{pane_current_path}"
  - name: Split up
    key: k
    command: "splitw -v -c #{pane_current_path} \\; swap-pane -s '-'"
  - name: Split left
    key: h
    command: "splitw -h -c #{pane_current_path} \\; swap-pane -s '-'"
  - name: Kill pane
    key: x
    command: 'confirm -p "Kill pane? (y/n)" killp'
  - separator: true
  - name: +Windows
    key: w
    menu:
      - name: Last
        key: tab
        command: last-window
      - name: Choose
        key: w
        command: choose-tree -Zw
      - name: Previous
        key: p
        command: previous-window
      - name: Next
        key: n
        command: next-window
      - name: New
        key: c
        command: "neww -c #{pane_current_path}"
      - separator: true
      - name: +Layout
        key: l
        menu:
          - name: Next
            key: l
            command: nextl
            transient: true
          - name: Tiled
            key: t
            command: "selectl tiled"
          - name: Horizontal
            key: h
            command: "selectl even-horizontal"
          - name: Vertical
            key: v
            command: "selectl even-vertical"
          - name: Horizontal main
            key: H
            command: "selectl main-horizontal"
          - name: Vertical main
            key: V
            command: "selectl main-vertical"
      - name: Rotate
        key: o
        command: rotatew
        transient: true
      - separator: true
      - name: Rename
        key: R
        command: command-prompt -I "#W" "renamew -- \"%%\""
      - name: Kill
        key: X
        command: 'confirm -p "Kill window #W? (y/n)" killw'
  - name: +Panes
    key: p
    menu:
      - name: Choose
        key: p
        command: displayp -d 0
      - separator: true
      - name: Left
        key: h
        command: selectp -L
      - name: Down
        key: j
        command: selectp -D
      - name: Up
        key: k
        command: selectp -U
      - name: Right
        key: l
        command: selectp -R
      - separator: true
      - name: Zoom
        key: z
        command: resizep -Z
      - name: +Resize
        key: r
        menu:
          - name: Left
            key: h
            command: resizep -L
            transient: true
          - name: Down
            key: j
            command: resizep -D
            transient: true
          - name: Up
            key: k
            command: resizep -U
            transient: true
          - name: Right
            key: l
            command: resizep -R
            transient: true
          - name: Left more
            key: H
            command: resizep -L 10
            transient: true
          - name: Down more
            key: J
            command: resizep -D 10
            transient: true
          - name: Up more
            key: K
            command: resizep -U 10
            transient: true
          - name: Right more
            key: L
            command: resizep -R 10
            transient: true
      - name: Swap left
        key: H
        command: swapp -t "{left-of}"
      - name: Swap down
        key: J
        command: swapp -t "{down-of}"
      - name: Swap up
        key: K
        command: swapp -t "{up-of}"
      - name: Swap right
        key: L
        command: swapp -t "{right-of}"
      - name: Break
        key: "!"
        command: break-pane
      - separator: true
      - name: Mark
        key: m
        command: selectp -m
      - name: Capture
        key: C
        command: capture-pane
      - name: Kill
        key: X
        command: 'confirm -p "Kill pane? (y/n)" killp'
  - name: +Buffers
    key: b
    menu:
      - name: Choose
        key: b
        command: choose-buffer -Z
      - name: List
        key: l
        command: lsb
      - name: Paste
        key: p
        command: pasteb
  - name: Copy mode
    key: c
    command: copy-mode
  - name: +Sessions
    key: s
    menu:
      - name: Choose
        key: s
        command: choose-tree -Zs
      - name: New
        key: N
        command: new
      - name: Rename
        key: r
        command: rename
  - name: +Client
    key: C
    menu:
      - name: Choose
        key: c
        command: choose-client -Z
      - separator: true
      - name: +Plugins
        key: P
        menu:
          - name: Install
            key: i
            command:
              run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/install_plugins
          - name: Update
            key: u
            command:
              run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/update_plugins
          - name: Clean
            key: c
            command:
              run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/clean_plugins
      - name: Detach
        key: D
        command: detach
      - separator: true
      - name: Reload config
        key: r
        macro: reload-config
  - separator: true
  - name: Time
    key: T
    command: clock-mode
  - name: Messages
    key: "~"
    command: show-messages
  - name: Keys
    key: "?"
    command: list-keys -N
